---
title: "EDA_NY_taxi"
author: "Team 7"
date: "December 3, 2016"
output:
  html_notebook: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(dplyr)
library(leaflet)

rm(list=ls(all=TRUE))

```


```{r}
ride.counts <- read_csv("./data/count_table_total.csv")

```

## Trying a first map
```{r}
m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=-73.84267, lat=40.86516, popup="New York") %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolylines(lng = c(-73.84267,-73.85), lat = c(40.86516, 40.85) )

m <- addPolylines(m, lng = c(-73.84267,-73.85), lat = c(40.86516, 40.86),
                  weight = 10)
m <- addPolylines(m, lng = c(-73.84267,-73.9), lat = c(40.86516, 40.86),
                  weight = 20)
m  # Print the map
```

Summarizing over the whole database
```{r}

ride.counts.all <- ride.counts %>% 
  dplyr::group_by(pickup_lon, pickup_lat, dropoff_lon, dropoff_lat, color) %>%
  dplyr::summarise(total.count = sum(n)) %>% as.data.frame()

#ride.counts.all$total.count <- as.numeric(ride.counts.all$total.count)


ride.counts.filter.threshold <- dplyr::filter(ride.counts.all, total.count >= 30000)

ride.counts.filter.threshold[,6] <- as.integer(as.character(ride.counts.filter.threshold[,6]))

dim(ride.counts.filter.threshold)
```


```{r}
#####
## Arrow painting function ##
#####

## 1. map has to be a leaftlet map, already defined in a variable

## 2. Arrow.data has to have the following columns:
# pickup_lon
# pickup_lat
# dropoff_lon
# dropoff_lat
# total.count


get.arrowhead <- function(data.line){

  # Convert to numeric without names
  data.line <- as.numeric(data.line)

  # Vector with direction of arrow.
  dx <- data.line[3] - data.line[1]
  dy <- data.line[4] - data.line[2]

  # normalize
  length <- sqrt(dx * dx + dy * dy)
  unitDx <- dx / length
  unitDy <- dy / length

  # increase this to get a larger arrow head
  arrowHeadBoxSize = 0.001

  # These are the coordinates to paint the arrow head (basically 2 lines)
  x1 = (data.line[3] - unitDx * arrowHeadBoxSize - unitDy * arrowHeadBoxSize)
  y1 = (data.line[4] - unitDy * arrowHeadBoxSize + unitDx * arrowHeadBoxSize)
  x2 = (data.line[3] - unitDx * arrowHeadBoxSize + unitDy * arrowHeadBoxSize)
  y2 = (data.line[4] - unitDy * arrowHeadBoxSize - unitDx * arrowHeadBoxSize)
  
  final.matrix <- matrix(c(x1, y1, data.line[3], data.line[4], 
                           x2, y2, data.line[3], data.line[4]), 
                         ncol = 4, byrow = TRUE)
  return(final.matrix)
}

paint.arrows <- function(map, arrow.data){
  
  #arrow.data <- as.matrix(arrow.data)
  
  for(i in 1:nrow(arrow.data)){
    
    # Get Data from row
    lng.x = c(arrow.data[i,1], arrow.data[i,3])
    lat.x = c(arrow.data[i,2], arrow.data[i,4])
    weight.x = arrow.data[i,6]
    maxweight = max(arrow.data[,6])
    line.weight = as.numeric(weight.x / maxweight * 20)
    
    taxi.color <- ""
    if(arrow.data[i,5] == "yellow"){
      taxi.color <- "orange"
    }
    else{
      taxi.color <- arrow.data[i,5]
    }
    
    # Paint line
    map <- addPolylines(map, lng = lng.x, lat = lat.x, weight = line.weight, color = taxi.color)
    
    #head(ride.counts.filter.threshold)    
    ## Paint Arrow Heads
    
    # Get Data of arrow head
    arrow.head <- get.arrowhead(arrow.data[i,1:4])
    # Check if we had errors (possible because origin and destination are the same)
    error.values <- sum(is.na(arrow.head))
    
    # If everything OK, we calculate and paint
    if(error.values == 0){
      lng.arrow.1 <- c(arrow.head[1,1], arrow.head[1,3])
      lat.arrow.1 <- c(arrow.head[1,2], arrow.head[1,4])
      lng.arrow.2 <- c(arrow.head[2,1], arrow.head[2,3])
      lat.arrow.2 <- c(arrow.head[2,2], arrow.head[2,4])
  
      # Paint Arrow Head
      map <- addPolylines(map, lng = lng.arrow.1, lat = lat.arrow.1, 
                          weight = line.weight, color = taxi.color)    
      map <- addPolylines(map, lng = lng.arrow.2, lat = lat.arrow.2, 
                          weight = line.weight, color = taxi.color)        
    }
  }  
  
  return(map)
}

```


```{r, fig.width=10}
n <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addProviderTiles("CartoDB.Positron")

n <- paint.arrows(n, ride.counts.filter.threshold)

n  # Print the map
```

